Develop
JaimeLoaiza/ProyectVisual.Net pull request #1
Opened 2019-11-25 04:21 UTC by JaimeLoaiza

Revisa los Ejercicios y realizame las observaciones y/o cambios que hayan que realizar en ellos.

2019-11-25 05:04 UTC, MauroCaro commented
Primeramente te voy a invitar a que a consciencias leas esto

https://geeks.ms/windowsplatform/2017/04/18/como-generar-mejores-pull-requests/

Esto te va a permitir tener mejores herramientas para ser consciente de como hacer unos buenos PR y espero que para los próximos sean de mejor calidad.

2019-11-25 21:39 UTC, MauroDecodificado requested changes
Por favor prestar mucha atención a lo que se pide, comprensión lectora de los algoritmos

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +public class Class1
Que es class1? eso esta incorrecto, por favor hemos hablado varias veces sobre el nombramiento adecuado de las clases, metodos y variables, corregirlo!

```suggestion
public class EjerciciosDiaUno
```

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +	{
Porque el constructor ser abre y se cierra en la linea 33? Esta incorrecto, si no se hace nada en el constructor por favor, eliminelo

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +        int Resultado = 0;
variables inician en minuscula

```suggestion
        int resultado = 0;
```

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +        int CalcularResultado(int number1, int number2)
1) El enunciado del documento dice **devuelva en String el resultado**
2) En el documento dice. **La clase debe ser pública al igual que todos sus métodos**
3) Se podria cambiar las variables solo texto directamente en vez de usar numero en el
4) Si se va a manejar todo en ingles, DEBE SER TODO EN INGLES, o si lo quiere manejar todo en español DEBE SER TODO EN ESPAÑOL, no mezclar idiomas

```suggestion
       public  String CalcularResultado(int numeroUno, int numeroDos)
```

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +        int CalcularResultado(int number1, int number2, int number3)
Mismas sugerencias realizadas para el metodo calcular resultado anterior

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +    public Class2()
Qué es Class2?

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +            int N;
Qué es N?

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +        static void Main(string[] args)
Porqué hay otros Main?

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +            if (N >= 1000)
Esta logica no corresponde con el ejercicio numero 2, el ejercicio numero dos costa en que dado un numero cualquiera, ejemplo:

2'310.294 debe devolver su **ultimo** digito, en este caso el numero 4 porque es su ultimo numero, no decirme de cuantas cifras es el numero ingresado

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +    public Class3()
Qué es clase 3?

2019-11-25 21:39 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +        static void Main(string[] args)
Porque hay un 3 main?

2019-11-25 22:03 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +public class Class1
Realizare una reestructuración del Ejercicio # 1 de .Net a lo largo y ancho del código, nombramientos de clases, métodos y variables, incluso trabajarlo en un solo idioma; aprovechare que me funciona. Eliminare lo que no haga falta dentro del código como son los Main, y también nombrar a todos los métodos públicos.

2019-11-25 22:04 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +	{
Lo tendré presente, ya que no me di cuenta de ello dentro del ejercicio a razón de que me corrió correctamente.

2019-11-25 22:05 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +        int Resultado = 0;
Realizare una reestructuración del Ejercicio # 1 de .Net a lo largo y ancho del código, nombramientos de clases, métodos y variables.

2019-11-25 22:08 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +        int CalcularResultado(int number1, int number2)
1. No iniciare un ejercicio hasta no comprenderlo a cabalidad.
2. Reestructurare el nombramientos de clases, métodos y variables, y también nombrare a todos los métodos públicos.
3. Acataré tu consejo..
4. Trabajaré en un solo idioma.

2019-11-25 22:09 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +        int CalcularResultado(int number1, int number2, int number3)
Reestructuración de Código Ejercicio # 1

2019-11-25 22:09 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +            int N;
Definiré correctamente el nombramiento de variables

2019-11-25 22:13 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +        static void Main(string[] args)
Por razón de que el método Main le da entrada al procedimiento... pero ya caí en la cuenta de que no es buena practica y no es lo correcto. No debo de confundir ejecutar en un solo método todo el código con establecer un orden por método correspondiente a lo requerido.

2019-11-25 22:18 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +            if (N >= 1000)
Esto si me extraña ... y mucho... ayer lo ejecute en varias oportunidades y siempre me arrojo los resultados correctos, partiendo de una cifra, hasta digitar una cifra tan alta como los nuevos números de cédula.
El código no cuenta cuantas cifras tiene el número ingresado....RARO...
LO REVISARE NUEVAMENTE, y te informo al respecto.

2019-11-25 22:20 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +    public Class3()
Esto es a razón de: "UNA CLASE POR MÉTODO"; realmente lo mal interpreté. es: UNA CLASE PARA VARIOS MÉTODOS.
Realizaré las correcciones pertinentes.

2019-11-25 22:21 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +        static void Main(string[] args)
Ya lo expuse anteriormente...

2019-11-25 23:56 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +        static void Main(string[] args)
Unicamente debe existir un metodo main

2019-11-25 23:59 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +        static void Main(string[] args)
Correcto, pero no he podido hacer correr el programa con los otros dos métodos; solo me corre el primero que ponga en la clase.

2019-11-26 00:01 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +        static void Main(string[] args)
Ya he hecho varios cambios .... y nada, continuare consultando un ratico más.

2019-11-26 00:02 UTC, JaimeLoaiza commented on EjerciciosDiaUno.cs
> +            if (N >= 1000)
Me sigue funcionando muy bien el código...

2019-11-26 00:06 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +            if (N >= 1000)
Estás en lo correcto el ejercicio funciona perfectamente, como sugerencia puedes simplificar de la siguiente manera el ((N % 1000) % 100) % 10):

Para los números positivos te debería funcionar con solo 

(N % 10)

Para los negativos debes buscar la manera de obtener el ultimo digito.

Excelente, tuve que sacar papel y lápiz para poder entender bien el porque del ((N % 1000) % 100) % 10) y finalmente vi que matematicamente se resolvia así.

2019-11-26 00:08 UTC, MauroCaro commented on EjerciciosDiaUno.cs
> +    public Class3()
Correcto, no hay necesidad de crear clase para en el poner solo un metodo, simplemente una clase con todos los ejercicios en el 👍

2019-11-27 00:50 UTC, MauroDecodificado requested changes

2019-11-27 00:50 UTC, MauroDecodificado commented on EjercicioDiaUno.cs
> +            resultado = numero1 + numero2;
Esta logica debe de ir en el metodo CalcularResultado

2019-11-27 00:50 UTC, MauroDecodificado commented on EjercicioDiaUno.cs
> +            Convert.ToString(resultado, null);
Estoy casi seguro que esto es innecesario

2019-11-27 00:50 UTC, MauroDecodificado commented on EjercicioDiaUno.cs
> +            resultado = (numero1 + numero2) * numero3;
Esta logica debe ir en la sobrecarga del metodo CalcularResultado

2019-11-27 00:50 UTC, MauroDecodificado commented on EjercicioDiaUno.cs
> +            Convert.ToString(resultado, null);
Revisa si es necesario este convert, no veo que sea necesario

2019-11-27 00:50 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +                Console.WriteLine("El Número digitado es Negativo" + "; " + "Su ültimo digito es: " + (cifra % 10));
La logica debe ir en el metodo CalcularUltimoDigito, si ya se encuentra ahi, entonces llamarlo desde acá al metodo

2019-11-27 00:50 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +            pulgadas = centimetros * 0.39370;
La logica debe ir en ConvertirCentimetrosAPulgadas

2019-11-27 00:51 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +            EjercicioDiaUno clase = new EjercicioDiaUno();
Haga esta variable publica para que la pueda acceder en distintas partes de la clase y tenga acceso, por favor revisa la imagen que te envie anoche

2019-11-27 22:33 UTC, JaimeLoaiza reviewed
Se realizan Correcciones en EjerciciosDiaUno y Clean Code; se ejecuta proyecto de manera exitosa.

2019-11-27 22:33 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +            Convert.ToString(resultado, null);
Hecho...

2019-11-28 05:51 UTC, MauroDecodificado requested changes

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            EjercicioDiaUno ejercicioDia = new EjercicioDiaUno();
No es necesaria esta variable, puedes eliminar toda esta declaracion de variable e instancia porque en la linea 11 ya tienes la declaracion de la variable global y la instancia de la variable la estas haciendo en la linea 15 en el main, entonces estas creando otra varialbe igual que en este punto no es necesaria porque ya tienes tu variable global que se llama ejercicioDia y la puedes llamar

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            Convert.ToString(resultado, null);
Pregunta, si es necesario este convert, si es asi para que sirve? si no es necesario por favor eliminalo

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            EjercicioDiaUno ejercicioDia = new EjercicioDiaUno();
Misma sugerencia que en el otro llamado:

No es necesaria esta variable, puedes eliminar toda esta declaracion de variable e instancia porque en la linea 11 ya tienes la declaracion de la variable global y la instancia de la variable la estas haciendo en la linea 15 en el main, entonces estas creando otra varialbe igual que en este punto no es necesaria porque ya tienes tu variable global que se llama ejercicioDia y la puedes llamar desde cualquier punto de la clase

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +                Console.WriteLine("El Número digitado es Negativo" + "; " + "Su ültimo digito es: " + (cifra % 10));
La logica de Cifra % 10 debe ir en el metodo CalcularUltimoDigito y llamar el metodo desde aquí

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +                Console.WriteLine("La última cifra del Número digitado es: " + (cifra % 10));
La logica de Cifra % 10 debe ir en el metodo CalcularUltimoDigito y llamar el metodo desde aquí

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            EjercicioDiaUno ejercicioDia = new EjercicioDiaUno();
Misma sugerencia que en el otro llamado:

No es necesaria esta variable, puedes eliminar toda esta declaracion de variable e instancia porque en la linea 11 ya tienes la declaracion de la variable global y la instancia de la variable la estas haciendo en la linea 15 en el main, entonces estas creando otra varialbe igual que en este punto no es necesaria porque ya tienes tu variable global que se llama ejercicioDia y la puedes llamar desde cualquier punto de la clase

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            resultado.ToString();
No es necesario esta linea ya que en el return, estas haciendo tambien resultado.ToString(), entones estas repitiendo dos veces y esta no es necesaria. eliminala por favor

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            resultado.ToString();
No es necesario esta linea ya que en el return, estas haciendo tambien resultado.ToString(), entonces estas repitiendo dos veces y esta no es necesaria. eliminala por favor

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +        public int CalcularUltimoDigito(int cifra)
Recuerda usar este metodo en el llamado dos 😄

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +                Console.WriteLine();
Elimina los console de este metodo, recuerda que acá solo debe ir unicamente lógica

2019-11-28 05:51 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +
Elimina espacios innecesarios

2019-11-28 14:58 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            EjercicioDiaUno ejercicioDia = new EjercicioDiaUno();
ok, entendido.

2019-11-28 15:10 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            Convert.ToString(resultado, null);
No, no es necesario este Convert, y tampoco cumple una funcionalidad; ya que se encuentra ubicado despues de la línea de respuesta. A razón de que en la lógica ya establecí devolver un String como respuesta.

Ya fue eliminado del código.

2019-11-28 17:28 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            EjercicioDiaUno ejercicioDia = new EjercicioDiaUno();
Realizando pruebas con respecto a la línea 33 en relación con la línea 11 y 15 del código en mención, NO es posible eliminarla. 

> "porque en la linea 11 ya tienes la declaración de la variable global y la instancia de la variable la estas haciendo en la linea 15 en el main"

;si elimino la variable de la línea 33  reventaría el código en la línea 34 **por objeto no establecido**;
Con la variable declarada en la línea 33 e instanciada en el Main y eliminar la variable en la línea 11, el código me ejecuta sin ningún problema. Es clave denotar la instancia dentro del Main y dentro de los métodos, eso seria mas que suficiente para correr los métodos dentro de la clase.

2019-11-28 17:29 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            EjercicioDiaUno ejercicioDia = new EjercicioDiaUno();
Misma respuesta del PR anterior.

2019-11-28 17:45 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +                Console.WriteLine("El Número digitado es Negativo" + "; " + "Su ültimo digito es: " + (cifra % 10));
La lógica (Cifra % 10) no la puedo quitar de la concatenación de la respuesta, tras que se necesita para que se muestre el último dígito del número ingresado. Si esta lógica la ubico en el método CalcularUltimoDigito, no mostraría el último dígito del número ingresado a pesar de que llame al método.

2019-11-28 17:46 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +                Console.WriteLine("La última cifra del Número digitado es: " + (cifra % 10));
Igual respuesta del PR anterior.

2019-11-28 17:48 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            resultado.ToString();
Correcta la apreciación. Se retira línea 83 de código.

2019-11-28 17:49 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            resultado.ToString();
Correcta la apreciación. Se retira línea 83 de código.

2019-11-28 17:52 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +        public int CalcularUltimoDigito(int cifra)
Método llamado dos, línea 52 llamando a la lógica por el método 

> **CalcularUltimoDigito** 

ejecución del llamado. Llamado exitoso.

2019-11-28 18:27 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +                Console.WriteLine();
De acuerdo, solo va en este método el: **return cifra;**, ya que en el método de ejecución de la lógica va la lógica.

Realizado.

2019-11-28 18:49 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +
ok.

2019-11-29 05:29 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +            return cifra;
Estas creando un metodo que recibe una cifra y devuelve eso mismo, esta logica esta completamente erronea, si se hiciera eso asi que finalidad tiene un metodo que reciba y devuelva exactamente lo mismo, lo que te menciono acá es que este metodo debe contener la logica para tanto el condicional de positivos y del modulo 10 con el de negativos y debes retornar al final el calculo de eso. Esta incorrecto este codigo y lo que hiciste no aporta al codigo, por favor verifica y trae la logica del Llamar ejercicio dos a este metodo

2019-11-29 05:29 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +                Console.WriteLine("El Número digitado es Negativo" + "; " + "Su ültimo digito es: " + (cifra % 10));
Si te puedes llevar la logica al metodo, por favor verificalo y cambialo

2019-11-29 05:33 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            EjercicioDiaUno ejercicioDia = new EjercicioDiaUno();
Por favor seguir las sugerencias que te estoy haciendo lo que estas haciendo NO ES necesario NI ES mas eficiente, crea una variable global en la clase, haz la instancia en el main en su primera linea dentro de el y no es necesario volver a crear otras instancias. No es mas eficiente como bien dices y porqué?

En 3 metodos diferentes estas creando 3 veces la misma variable en memoria, eso significa que estas cargando 3 variables las cuales son completamente iguales. Debes tener una sola variable global, instanciarla esa variable en el main y usarla a travez de la clase.

2019-11-29 05:35 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +                Console.WriteLine();
Lo que hiciste no tiene sentido agregar un metodo para que reciba un parametro y devuelvas inmeditamente el parametros:

En ese caso, qué sentido tiene el metodo? Eso se convertiria en codigo basura y que no hace nada, por favor migra la logica completamente, asi como se hizo con los otros dos ejercicios

2019-11-29 05:46 UTC, MauroDecodificado requested changes

2019-11-29 05:46 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +            EjercicioDiaUno ejercicioDia = new EjercicioDiaUno();
Esto debe ser una variable global y unicamente acá instanciarla

2019-11-29 05:46 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +            Convert.ToString(resultado, null);
Esto es necesario? si eliminaste los otros porqué conservas esto?

2019-11-29 05:46 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaDos.cs
> +﻿using System;
Qué hace esta clase del dia dos en este PR?

2019-11-29 05:46 UTC, MauroCaro commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
>      class EjercicioDiaUno
Porque hay otra clase que se llama EjercicioDiaUno **nuevamente**? porqué el desorden en realizar el codigo?

2019-11-30 04:53 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
>      class EjercicioDiaUno
Limpieza realizada..

2019-11-30 04:53 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaDos.cs
> +﻿using System;
PR actualizado...

2019-11-30 04:54 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +            Convert.ToString(resultado, null);
linea 35 eliminada..

2019-11-30 04:55 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +            EjercicioDiaUno ejercicioDia = new EjercicioDiaUno();
Variable instanciada y declarada en su método apropiado..

2019-11-30 04:58 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +            return cifra;
Se verifica instrucción del método CalcularUltimoDigito y se lleva la lógica del llamarEjercicioDos al método CalcularUltimoDigito.

2019-11-30 05:07 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +                Console.WriteLine();
Se aplica requerimiento...

2019-11-30 05:08 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +        public int CalcularUltimoDigito(int cifra)
ok

2019-11-30 05:49 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +                Console.WriteLine("El Número digitado es Negativo" + "; " + "Su ültimo digito es: " + (cifra % 10));
ok

2019-11-30 05:50 UTC, JaimeLoaiza commented on Proyecto_Visual.Net/EjercicioDiaUno.cs
> +            EjercicioDiaUno ejercicioDia = new EjercicioDiaUno();
ok

2019-11-30 16:03 UTC, MauroDecodificado requested changes

2019-11-30 16:03 UTC, MauroDecodificado commented on EjercicioDiaUno.cs
> +            Console.WriteLine("El Número digitado es Negativo" + "; " + "Su ültimo digito es: " + (cifra % 10));
Ya no es necesario realizar el cifra %10, ya que en la linea 46 estas llamando el CalcularUltimoDigito y estas actualizando la misma variable cifra.

```suggestion
            Console.WriteLine("El Número digitado es Negativo" + "; " + "Su ültimo digito es: " + cifra);
```

2019-11-30 16:03 UTC, MauroDecodificado commented on EjercicioDiaUno.cs
> +            Console.WriteLine("La última cifra del Número digitado es: " + (cifra % 10));
Puedes unificar una solo WriteLine para mostrar el resultado

2019-11-30 16:03 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +                _ = (cifra % 10);
Y usarla para asignarla aquí 

```suggestion
                ultimoDigito = (cifra % 10);
```

2019-11-30 16:03 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +            else if (cifra >= 0)
Este condicional sobra, porque mira

Si el numero es < 0 entonces haces cifra % 10 y si es >= 0 entonces haces lo mismo cifra % 10

Simplemente entonces convierte cifra a % 10, porque tienes dos condicionales que realizan lo mismo. Sobra el elseif.

2019-11-30 16:03 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +                cifra = cifra;
```suggestion
           ultimoDigito = cifra
```

2019-11-30 16:03 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +            return cifra;
```suggestion
            return ultimoDigito;
```

2019-11-30 17:09 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +            Console.WriteLine("El Número digitado es Negativo" + "; " + "Su ültimo digito es: " + (cifra % 10));
Hecho y entendido

2019-11-30 17:11 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +            Console.WriteLine("La última cifra del Número digitado es: " + (cifra % 10));
Correcto, en una sola línea arroja la respuesta...

2019-11-30 17:13 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +                _ = (cifra % 10);
Si Señor, es correcta tu apreciación...

2019-11-30 17:47 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +            else if (cifra >= 0)
Cambios en modo prueba satisfactorios.

2019-11-30 17:47 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +                cifra = cifra;
Cambios en modo prueba satisfactorios

2019-11-30 17:47 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +            return cifra;
Cambios en modo prueba satisfactorios

2019-11-30 19:08 UTC, MauroDecodificado requested changes

2019-11-30 19:08 UTC, MauroCaro commented on EjercicioDiaUno.cs
> +            else if (cifra >= 0)
Este condicional no es necesario, logicamente no aporta nada


```suggestion
            else if (cifra >= 0)
```

2019-11-30 21:17 UTC, JaimeLoaiza commented on EjercicioDiaUno.cs
> +            else if (cifra >= 0)
Correcto, analizado, testeado y comprobado. OK

2019-12-01 07:19 UTC, MauroDecodificado approved these changes
Buen trabajo, finalmente aprovado!

2019-12-01 07:30 UTC, merged