uploading corrected file to repository
JaimeLoaiza/ProyectVisual.Net pull request #3
Opened 2019-12-03 08:25 UTC by JaimeLoaiza

Se comitea EjercicioDiaDos

2019-12-03 15:26 UTC, MauroDecodificado requested changes

2019-12-03 15:26 UTC, MauroCaro commented on EjercicioDiaDos.cs
>              int areacuadrado;
Borra los espacios por favor, linea 74!

2019-12-03 15:26 UTC, MauroCaro commented on EjercicioDiaDos.cs
> +        public string DeterminarNumero(int numero)
Vuelvo y te digo: Que sentido tiene crear un si - sino (If-else), si vas a hacer exactamente lo mismo?

La logica de este ejercicio no esta bien yo no te estoy pidiendo que me devuelvas el numero en string, te estoy pidiendo que me devuelvas un string con positivo o negativo

2019-12-03 15:26 UTC, MauroCaro commented on EjercicioDiaDos.cs
> +            if (numero >= 0)
Estos condicionales no deben de ir acá: Tu vas a llamar un metodo que te va a devolver un string con: positivo o con negativo y luego haces  un

```suggestion
          Console.WriteLine("Número es: "  + determinenumero));
```

2019-12-03 15:26 UTC, MauroCaro commented on EjercicioDiaDos.cs
>                  determinenumero = numero;
Si es mayor o igual a o entonces determine numero va a ser igual a lo que llego por parametro:

Es decir si enviaron 3 como parametro vas a hacer 3 a determinenumero

2019-12-03 15:26 UTC, MauroCaro commented on EjercicioDiaDos.cs
>                  determinenumero = numero;
Sino  determine numero va a ser igual a lo que llego por parametro:

Es decir si enviaron 3 como parametro vas a hacer 3 a determinenumero

2019-12-03 15:26 UTC, MauroCaro commented on EjercicioDiaDos.cs
> +            return numero.ToString();
Como te mencione NO te estoy pidiendo que devuelvas el numero en string, el enunciado dice
debe retornar positivo o negativo, no el numero en string

2019-12-03 15:26 UTC, MauroCaro commented on EjercicioDiaDos.cs
> +            if (multiplo % 2 == 0 && multiplo % 3 == 0)
Porque esto esta acá? esta logica debe estar en el metodo CalculoDeMultiplos, estas repitiendo exactamente lo mism: el ejercicio dice que se debe retornar un string con el mensaje de su operacion.

```suggestion
           Console.WriteLine(numerodivisible);
```

2019-12-03 15:26 UTC, MauroCaro commented on EjercicioDiaDos.cs
> +            return multiplo.ToString();
Vuelvo y digo estas retornando el numero en string, el ejercicio NO dice que se devuelva un numero en string dice que devuelva el string con la operacion 

Si el numero ingresado es únicamente múltiplo de 2, **debe retornar** “Numero divisible por 2”
- Si el numero ingresado es únicamente múltiplo de 3, **debe retornar** “Numero divisible por 3”
- Si el numero ingresado es múltiplo de ambos (2 y 3), **debe retornar** “Numero divisible por ambos”
- En caso de que el número no sea divisible por 2 o 3, **debe retornar** “Número no divisible por 2 o 3”

2019-12-03 15:26 UTC, MauroCaro commented on EjercicioDiaDos.cs
> +            else if (multiplo % 1 == 0 || multiplo % 2 == 0 || multiplo % 3 == 0)
Porque hay un % 1?

2019-12-03 15:26 UTC, MauroCaro commented on EjercicioDiaDos.cs
> +        public string CalculoDeMultiplos(int multiplo)
En este metodo deben de haber 3 condicionales y un sino

- Si es multiplo de 2 o 3
- Si es multipo de 3
- Si es multiplo de 2
- Sin multiplos

Corrige la logica

2019-12-03 20:27 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
>              int areacuadrado;
Hecho

2019-12-03 22:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +        public string CalculoDeMultiplos(int multiplo)
Cambios realizados a punto

2019-12-03 22:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            return multiplo.ToString();
Cambios realizados a punto

2019-12-03 22:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            if (multiplo % 2 == 0 && multiplo % 3 == 0)
Cambios realizados a punto

2019-12-03 22:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            return numero.ToString();
Cambios realizados a punto

2019-12-03 22:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
>                  determinenumero = numero;
Cambios realizados a punto

2019-12-03 22:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
>                  determinenumero = numero;
Cambios realizados a punto

2019-12-03 22:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            if (numero >= 0)
Cambios realizados a punto

2019-12-03 22:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +        public string DeterminarNumero(int numero)
Cambios realizados a punto

2019-12-03 22:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
>              int areacuadrado;
Cambios realizados a punto

2019-12-06 05:30 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
>              int areacuadrado;
Realizado

2019-12-06 05:30 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +        public string DeterminarNumero(int numero)
Realizado

2019-12-06 05:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            if (numero >= 0)
Realizado

2019-12-06 05:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
>                  determinenumero = numero;
Realizado

2019-12-06 05:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
>                  determinenumero = numero;
Realizado

2019-12-06 05:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            return numero.ToString();
Realizado

2019-12-06 05:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            if (multiplo % 2 == 0 && multiplo % 3 == 0)
Realizado

2019-12-06 05:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            return multiplo.ToString();
Realizado

2019-12-06 05:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            else if (multiplo % 1 == 0 || multiplo % 2 == 0 || multiplo % 3 == 0)
Realizado

2019-12-06 05:31 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +        public string CalculoDeMultiplos(int multiplo)
Realizado

2019-12-06 07:08 UTC, MauroCaro commented on EjercicioDiaDos.cs
> +            return multiplo.ToString();
Este returna ya no es necesario y porqué?

Te daras cuenta que en todos tus condicionales estas haciendo un return.

2019-12-06 07:08 UTC, MauroCaro commented on EjercicioDiaDos.cs
> +            return numero.ToString();
Este return tampoco es necesario

Porque tienes el si y el sino retornando, es decir nunca llegará  a este punto

2019-12-06 07:16 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            return numero.ToString();
captado y corregido... con razon esas dos lineas de código se tornaron tenues... ya no estaban activas..

2019-12-06 07:16 UTC, JaimeLoaiza commented on EjercicioDiaDos.cs
> +            return multiplo.ToString();
captado y corregido... con razon esas dos lineas de código se tornaron tenues... ya no estaban activas..

2019-12-06 07:23 UTC, MauroDecodificado approved these changes
Approved!

2019-12-06 07:23 UTC, merged